"""Hades — nightly Athenaeum consolidation pipeline.

Runs as a cron job. Performs:
  1. Distillation — extract canonical knowledge from vault sessions
  2. Health checks — ChromaDB vs filesystem consistency, INDEX coverage
  3. Archive management — identify and move stale/unlinked content
  4. Report generation — summary for the 7am delivery
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import time
from collections import defaultdict
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

_REAL_HOME = os.path.expanduser("~")
ATHENAEUM_ROOT = Path(f"{_REAL_HOME}/athenaeum")
CHROMA_DIR = Path(f"{_REAL_HOME}/.hermes/pantheon/chroma")
GRAPH_DB = Path(f"{_REAL_HOME}/.hermes/pantheon/graph.db")
HERMES_INBOX = Path(f"{_REAL_HOME}/pantheon/gods/messages/hermes")
INDEX_DESCRIPTION = (
    "Content in `{path}` is managed by Demeter and Mnemosyne.\n"
    "Files are auto-detected and embedded into the vector store on change."
)

# Files older than this (in days) are archive candidates if not linked in the graph
STALE_THRESHOLD_DAYS = 90

# Codex exclusion list — system codices we don't auto-archive or auto-distill
SYSTEM_CODEXES = {"Codex-Pantheon", "Codex-Apollo"}

# God memory codices (Codex-God-*) are EXCLUDED from ALL Hades processing.
# These are active living memory — dynamically written by gods, not canonical
# knowledge. The naming convention itself is the exclusion mechanism.
GOD_CODEX_PREFIX = "Codex-God-"

KNOWN_CODEXES = [
    "Codex-Forge", "Codex-Pantheon", "Codex-Infrastructure",
    "Codex-SKC", "Codex-Fiction", "Codex-Asclepius", "Codex-General",
    "Codex-Claude", "Codex-User", "Codex-Work", "Codex-Apollo",
]

EMBEDDABLE_EXTS = {".md", ".txt", ".json", ".yaml", ".yml"}
DISTILLED_DIR_NAME = "distilled"
ARCHIVE_DIR_NAME = "archive"
SESSIONS_DIR_NAME = "sessions"


def _get_all_codexes() -> List[str]:
    """Discover all Codex directories — union of hardcoded known + filesystem.

    New codexes created dynamically (e.g. during LLM compilation) are
    automatically discovered on the next Hades run.
    """
    fs_codexes: List[str] = []
    if ATHENAEUM_ROOT.is_dir():
        for d in sorted(ATHENAEUM_ROOT.iterdir()):
            if (
                d.is_dir()
                and d.name.startswith("Codex-")
                and d.name not in KNOWN_CODEXES
                and not d.name.startswith(GOD_CODEX_PREFIX)
            ):
                fs_codexes.append(d.name)
    return list(KNOWN_CODEXES) + fs_codexes


def _create_codex(name: str, description: str = "") -> bool:
    """Create a new Codex directory with INDEX.md.

    Args:
        name: The Codex name, e.g. 'Codex-HyMem'
        description: One-line description for the INDEX.md

    Returns:
        True if created, False if already exists.
    """
    codex_dir = ATHENAEUM_ROOT / name
    if codex_dir.exists():
        return False

    codex_dir.mkdir(parents=True, exist_ok=True)

    # Write INDEX.md
    index_path = codex_dir / "INDEX.md"
    index_content = f"""# {name} — Index

Parent: [{ATHENAEUM_ROOT.name}](../INDEX.md)
Last updated: {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}

{description}

Content in `{name}/` is managed by Demeter and Mnemosyne.
Files are auto-detected and embedded into the vector store on change.
"""
    index_path.write_text(index_content, encoding="utf-8")

    # Create standard subdirectories
    for sub in [DISTILLED_DIR_NAME, SESSIONS_DIR_NAME, ARCHIVE_DIR_NAME]:
        (codex_dir / sub).mkdir(parents=True, exist_ok=True)

    logger.info("  → ✨ Created new Codex: %s", name)

    # Add entry to CODEX_CLASSIFIERS so future sessions get auto-detected
    # Use the codex name minus "Codex-" as the primary keyword
    keyword = name.replace("Codex-", "", 1).lower().replace("-", " ")
    # Don't re-add if already there (race condition with parallel runs)
    existing_keywords = {kw for kws, _ in CODEX_CLASSIFIERS for kw in kws}
    if keyword not in existing_keywords:
        CODEX_CLASSIFIERS.insert(0, ([keyword], name))

    return True


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


class HadesReport:
    """Report generated by a Hades run."""

    def __init__(self):
        self.timestamp: str = datetime.now(timezone.utc).isoformat()
        self.health: Dict[str, Any] = {
            "codexes": {},
            "chroma_vs_fs": {},
            "orphans": {"chroma_only": [], "fs_unembedded": []},
            "missing_indexes": [],
            "stale_candidates": [],
        }
        self.distillation: Dict[str, Any] = {
            "sessions_processed": 0,
            "distilled_files_written": 0,
            "by_codex": {},
        }
        self.archive: Dict[str, Any] = {
            "files_archived": 0,
            "errors": [],
        }
        self.compilation: Dict[str, Any] = {
            "sessions_compiled": 0,
            "articles_created": 0,
            "articles_updated": 0,
            "articles_by_type": {"concept": 0, "connection": 0, "qa": 0},
            "transcripts_copied": 0,
            "errors": [],
            "batch_size": 0,
            "total_backlog": 0,
        }
        self.extraction: Dict[str, Any] = {
            "files_processed": 0,
            "files_failed": 0,
            "entities_extracted": 0,
            "relations_extracted": 0,
            "error": None,
        }
        self.shared_context: Dict[str, Any] = {
            "decisions_ingested": 0,
            "active_archived": 0,
            "athenaeum_entries": 0,
            "errors": [],
        }
        self.errors: List[str] = []

    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp,
            "health": self.health,
            "distillation": self.distillation,
            "archive": self.archive,
            "compilation": self.compilation,
            "extraction": self.extraction,
            "shared_context": self.shared_context,
            "errors": self.errors,
        }

    def to_markdown(self) -> str:
        """Format the report as a human-readable markdown summary."""
        lines = [
            f"# 🌙 Hades Nightly Report — {self.timestamp[:10]}",
            "",
            "## 📊 Codex Overview",
            "| Codex | Files | Embedded | Distilled | Sessions | Missing INDEX |",
            "|---|---|---|---|---|---|",
        ]

        for codex, info in sorted(self.health.get("codexes", {}).items()):
            missing = "⚠️" if codex in self.health.get("missing_indexes", []) else "✅"
            lines.append(
                f"| {codex} | {info.get('files', 0)} | {info.get('embedded', '?')} | "
                f"{info.get('distilled', 0)} | {info.get('sessions', 0)} | {missing} |"
            )

        lines.append("")

        # Chroma vs FS consistency
        orphans_fs = self.health.get("orphans", {}).get("fs_unembedded", [])
        orphans_c = self.health.get("orphans", {}).get("chroma_only", [])
        if orphans_fs or orphans_c:
            lines.append("## ⚠️ Consistency Issues")
            if orphans_fs:
                lines.append(f"- **{len(orphans_fs)} files not embedded in ChromaDB**")
            if orphans_c:
                lines.append(f"- **{len(orphans_c)} ChromaDB entries orphaned** (no matching file)")

        # Missing INDEXes
        missing = self.health.get("missing_indexes", [])
        if missing:
            lines.append(f"\n### Missing INDEX.md ({len(missing)})")
            for m in missing:
                lines.append(f"- {m}")

        # INDEX auto-creation report
        created = self.health.get("indexes_created", [])
        if created:
            lines.append(f"\n### ✅ INDEX.md Auto-Created ({len(created)})")
            for c in created:
                lines.append(f"- `{c}/INDEX.md` created")

        # Stale candidates
        stale = self.health.get("stale_candidates", [])
        if stale:
            lines.append(f"\n### 🗄️ Stale Candidates ({len(stale)})")
            lines.append("Files not modified in 90+ days:")
            for s in stale[:10]:
                lines.append(f"- {s['path']} (last modified: {s['last_modified'][:10]})")
            if len(stale) > 10:
                lines.append(f"- ... and {len(stale) - 10} more")

        # Distillation summary
        dist = self.distillation
        if dist.get("distilled_files_written", 0) > 0:
            lines.append(f"\n## 🔄 Distillation")
            lines.append(f"- Sessions processed: {dist.get('sessions_processed', 0)}")
            lines.append(f"- Distilled files written: {dist.get('distilled_files_written', 0)}")

        # Compilation summary
        comp = self.compilation
        if comp.get("sessions_compiled", 0) > 0 or comp.get("errors"):
            lines.append("")
            lines.append(f"\n## 🧠 LLM Compilation")
            lines.append(f"- Sessions compiled: {comp.get('sessions_compiled', 0)}")
            lines.append(f"- Articles created: {comp.get('articles_created', 0)}")
            lines.append(f"- Articles updated: {comp.get('articles_updated', 0)}")
            by_type = comp.get("articles_by_type", {})
            if any(by_type.values()):
                lines.append(f"  - Concepts: {by_type.get('concept', 0)}")
                lines.append(f"  - Connections: {by_type.get('connection', 0)}")
                lines.append(f"  - Q&A: {by_type.get('qa', 0)}")
            lines.append(f"- Transcripts copied: {comp.get('transcripts_copied', 0)}")
            backlog = comp.get("total_backlog", 0)
            if backlog > 0:
                lines.append(f"- Remaining backlog: {backlog}")
            if comp.get("errors"):
                for e in comp["errors"]:
                    lines.append(f"- ❌ {e}")
            new_cx_list = comp.get("new_codexes_created", [])
            if new_cx_list:
                lines.append(f"- ✨ New Codices: {', '.join(new_cx_list)}")

        # Archive summary
        arch = self.archive
        if arch.get("files_archived", 0) > 0 or len(arch.get("candidates", [])) > 0:
            lines.append("")
            lines.append(f"## 📦 Archive")
            lines.append(f"- Files archived: {arch.get('files_archived', 0)}")
            if arch.get("candidates"):
                lines.append(f"- Candidates found: {len(arch['candidates'])}")

        # Entity extraction summary
        extr = self.extraction
        if extr.get("entities_extracted", 0) > 0 or extr.get("error"):
            lines.append("")
            lines.append(f"## 🔗 Entity Extraction")
            if extr.get("error"):
                lines.append(f"- ❌ Error: {extr['error']}")
            else:
                lines.append(f"- Files processed: {extr.get('files_processed', 0)}")
                lines.append(f"- Entities extracted: {extr.get('entities_extracted', 0)}")
                lines.append(f"- Relations extracted: {extr.get('relations_extracted', 0)}")
                if extr.get("files_failed", 0) > 0:
                    lines.append(f"- ⚠️ Files failed: {extr['files_failed']}")

        # Shared context sweep summary
        sc = self.shared_context
        if sc.get("decisions_ingested", 0) > 0 or sc.get("active_archived", 0) > 0 or sc.get("athenaeum_entries", 0) > 0:
            lines.append("")
            lines.append(f"## 📋 Shared Context Sweep")
            lines.append(f"- Decisions ingested: {sc.get('decisions_ingested', 0)}")
            lines.append(f"- Active tasks archived: {sc.get('active_archived', 0)}")
            lines.append(f"- Athenaeum write entries noted: {sc.get('athenaeum_entries', 0)}")
            if sc.get("errors"):
                for e in sc["errors"]:
                    lines.append(f"- ⚠️ {e}")
        elif sc.get("errors"):
            lines.append("")
            lines.append(f"## 📋 Shared Context Sweep")
            for e in sc["errors"]:
                lines.append(f"- ⚠️ {e}")

        # New Codices created
        new_codexes = self.health.get("new_codexes", [])
        if new_codexes:
            lines.append("")
            lines.append(f"## ✨ New Codices Created ({len(new_codexes)})")
            for nc in new_codexes:
                lines.append(f"- **{nc.get('codex')}** — {nc.get('files_moved', 0)} files from '{nc.get('keyword', '?')}' cluster")

        # Errors
        if self.errors:
            lines.append(f"\n## ❌ Errors ({len(self.errors)})")
            for e in self.errors:
                lines.append(f"- {e}")

        lines.append("")
        lines.append("---")
        lines.append(f"_Report generated: {self.timestamp}_")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 1. Health checks
# ---------------------------------------------------------------------------


def _walk_codex_files(codex_root: Path) -> Dict[str, List[Path]]:
    """Walk a Codex directory and group files by subfolder.

    Returns: {
        "files": [all embeddable files excluding archive/distilled/sessions],
        "embeddable": [files that should be in ChromaDB],
        "sessions": [session log files],
        "distilled": [existing distilled files],
        "subdirs": [all subdirectories],
    }
    """
    result: Dict[str, List[Path]] = {
        "files": [],
        "embeddable": [],
        "sessions": [],
        "distilled": [],
        "subdirs": [],
    }

    for child in codex_root.iterdir():
        if child.is_dir():
            result["subdirs"].append(child)

    for f in codex_root.rglob("*"):
        if not f.is_file():
            continue
        ext = f.suffix.lower()
        rel = f.relative_to(codex_root)
        parts = rel.parts

        # Skip hidden files
        if f.name.startswith("."):
            continue
        # Skip INDEX.md — navigation, not content
        if f.name == "INDEX.md":
            continue

        # Categorize by subfolder
        if len(parts) > 1:
            parent = parts[0]
            if parent == ARCHIVE_DIR_NAME:
                continue  # Skip archive files entirely
            if parent == DISTILLED_DIR_NAME:
                result["distilled"].append(f)
                continue
            if parent == SESSIONS_DIR_NAME:
                result["sessions"].append(f)
                continue

        result["files"].append(f)
        if ext in EMBEDDABLE_EXTS:
            result["embeddable"].append(f)

    return result


def ensure_index_files(codex_root: Path) -> List[str]:
    """Auto-create INDEX.md for any subdirectory that's missing one.

    Returns a list of paths where INDEX.md was created.
    Also checks for file counts and content changes.
    """
    created = []
    parent_name = codex_root.name
    parent_rel = f"../INDEX.md"

    for child in sorted(codex_root.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue

        index_path = child / "INDEX.md"
        if index_path.exists():
            continue

        # Count files in this subdirectory
        file_count = sum(1 for f in child.rglob("*") if f.is_file() and not f.name.startswith("."))

        # Generate description
        if child.name == "sessions":
            desc = "Session logs for this Codex."
        elif child.name == "distilled":
            desc = "Distilled knowledge extracted from session logs."
        elif child.name == "archive":
            desc = "Superseded and archived content."
        elif file_count == 0:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")
        else:
            desc = INDEX_DESCRIPTION.format(path=f"`{parent_name}/{child.name}`")

        content = (
            f"# {child.name.capitalize()} — Index\n"
            f"Parent: [{parent_name}]({parent_rel})\n\n"
            f"{desc}\n"
        )
        index_path.write_text(content, encoding="utf-8")
        created.append(f"{parent_name}/{child.name}")
        logger.info("  → Created INDEX.md for %s/%s", parent_name, child.name)

    return created


def find_stale_files(
    codex_root: Path, days: int = STALE_THRESHOLD_DAYS
) -> List[Dict]:
    """Find files not modified in *days* that are eligible for archival.

    Skips: INDEX.md, files already in archive/, files in sessions/.
    """
    cutoff = datetime.now(timezone.utc).timestamp() - (days * 86400)
    stale = []

    for f in codex_root.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
            continue
        rel = f.relative_to(codex_root)
        parts = rel.parts
        if len(parts) > 1 and parts[0] in (ARCHIVE_DIR_NAME, SESSIONS_DIR_NAME, DISTILLED_DIR_NAME):
            continue
        if f.name == "INDEX.md":
            continue

        try:
            mtime = f.stat().st_mtime
            if mtime < cutoff:
                stale.append({
                    "path": str(rel),
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })
        except Exception:
            continue

    stale.sort(key=lambda x: x["last_modified"])
    return stale


def run_health_checks() -> Dict[str, Any]:
    """Run all health checks across the Athenaeum.

    Returns health dict matching HadesReport.health shape.
    """
    health: Dict[str, Any] = {
        "codexes": {},
        "chroma_vs_fs": {},
        "orphans": {"chroma_only": [], "fs_unembedded": []},
        "missing_indexes": [],
        "indexes_created": [],
        "stale_candidates": [],
        "chroma_count": None,
    }

    # Try to read ChromaDB for comparison
    chroma_counts: Dict[str, int] = {}
    try:
        import chromadb
        if CHROMA_DIR.is_dir():
            client = chromadb.PersistentClient(path=str(CHROMA_DIR))
            for col in client.list_collections():
                try:
                    name = col.name  # e.g. "pantheon_codex_forge"
                    # Parse the codex name back and normalize to KNOWN_CODEXES casing
                    parts = name.split("_", 2)
                    if len(parts) >= 3:
                        parsed = "Codex-" + parts[2].replace("_", "-")
                        # Case-insensitive match against KNOWN_CODEXES for correct casing
                        matched = next((c for c in KNOWN_CODEXES if c.lower() == parsed.lower()), None)
                        if matched:
                            chroma_counts[matched] = col.count()
                        else:
                            chroma_counts[parsed] = col.count()
                except Exception:
                    pass
        health["chroma_count"] = sum(chroma_counts.values()) if chroma_counts else None
    except ImportError:
        pass  # chromadb not available

    for codex_name in _get_all_codexes():
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        info = _walk_codex_files(codex_dir)
        health["codexes"][codex_name] = {
            "files": len(info["files"]),
            "embeddable": len(info["embeddable"]),
            "sessions": len(info["sessions"]),
            "distilled": len(info["distilled"]),
            "subdirs": len(info["subdirs"]),
        }

        # Auto-create INDEX.md for missing subdirectories
        created = ensure_index_files(codex_dir)
        health["indexes_created"].extend(created)

        # Check for persistent gaps (subdirs without INDEX.md despite creation attempt)
        # This catches edge cases like empty dirs or permission issues
        still_missing = []
        for child in codex_dir.iterdir():
            if child.is_dir() and not child.name.startswith("."):
                if not (child / "INDEX.md").exists():
                    still_missing.append(f"{codex_dir.name}/{child.name}")
        if still_missing:
            health["missing_indexes"].extend(still_missing)

        # Chroma vs FS comparison
        embeddable_count = len(info["embeddable"])
        chroma_count = chroma_counts.get(codex_name, 0)
        health["codexes"][codex_name]["embedded"] = chroma_count if chroma_count else 0
        health["chroma_vs_fs"][codex_name] = {
            "chroma": chroma_count,
            "fs_embeddable": embeddable_count,
            "delta": chroma_count - embeddable_count,
        }

        if chroma_count > embeddable_count:
            # Chroma has more than filesystem — some are orphaned
            pass  # Detailed orphan detection requires iterating IDs
        elif embeddable_count > chroma_count:
            for f in info["embeddable"]:
                health["orphans"]["fs_unembedded"].append(str(f.relative_to(ATHENAEUM_ROOT)))
                if len(health["orphans"]["fs_unembedded"]) > 50:
                    break

        # Find stale files
        stale = find_stale_files(codex_dir)
        health["stale_candidates"].extend(stale)

    return health


# ---------------------------------------------------------------------------
# 2. Distillation
# ---------------------------------------------------------------------------


def distill_sessions(codex_name: str, codex_root: Path) -> Dict[str, int]:
    """Extract distilled knowledge from session logs.

    For each session file in codex/sessions/, extracts:
    - Distinct topics mentioned (from markdown headers, bold terms, bullet points)
    - Code blocks
    - Decisions and conclusions (lines after "Decision:", "Conclusion:", etc.)

    Writes a distilled summary to codex/distilled/.
    """
    sessions_dir = codex_root / SESSIONS_DIR_NAME
    distilled_dir = codex_root / DISTILLED_DIR_NAME
    distilled_dir.mkdir(parents=True, exist_ok=True)

    sessions = sorted(sessions_dir.glob("*.md")) if sessions_dir.is_dir() else []
    files_written = 0

    # Known signal patterns for extraction
    topic_pattern = re.compile(r"^#{1,3}\s+(.+)", re.MULTILINE)
    decision_pattern = re.compile(r"^\s*(?:Decision|Conclusion|Result|Outcome|Resolution)\s*[:\-–—]\s*(.+)", re.IGNORECASE | re.MULTILINE)
    bullet_pattern = re.compile(r"^\s*[-*+]\s+(.+)", re.MULTILINE)
    bold_pattern = re.compile(r"\*\*(.+?)\*\*")
    code_block_pattern = re.compile(r"```(\w*)\n(.*?)```", re.DOTALL)

    for session_path in sessions:
        try:
            content = session_path.read_text(encoding="utf-8")
        except Exception:
            continue

        if len(content.strip()) < 200:
            continue  # Skip empty or near-empty sessions

        # Extract metadata from frontmatter
        metadata = {}
        fm_match = re.match(r"^---\n(.*?)\n---", content, re.DOTALL)
        if fm_match:
            for line in fm_match.group(1).strip().split("\n"):
                if ":" in line:
                    k, _, v = line.partition(":")
                    metadata[k.strip()] = v.strip()
            content = content[fm_match.end():]

        # Extract topics (headers)
        topics = []
        for m in topic_pattern.finditer(content):
            t = m.group(1).strip()
            if t and t not in topics:
                topics.append(t)

        # Extract decisions
        decisions = [m.group(1).strip() for m in decision_pattern.finditer(content) if m.group(1).strip()]

        # Extract bold/key terms
        key_terms = list(set(m.group(1) for m in bold_pattern.finditer(content) if m.group(1)))

        # Extract code blocks
        code_blocks = []
        for m in code_block_pattern.finditer(content):
            lang = m.group(1) or "text"
            snippet = m.group(2).strip()
            if snippet:
                code_blocks.append({"language": lang, "content": snippet[:500]})

        # Extract bullet points (first ~20)
        bullets = [m.group(1).strip() for m in bullet_pattern.finditer(content) if m.group(1).strip()][:25]

        if not topics and not decisions and not bullets:
            continue  # Nothing substantive to distill

        # Build distilled document
        session_id = session_path.stem
        lines = [
            f"# Distilled: {session_id}",
            "",
            f"Source: `{codex_name}/{SESSIONS_DIR_NAME}/{session_path.name}`",
            f"Distilled at: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        if metadata:
            lines.append("## Metadata")
            for k, v in metadata.items():
                lines.append(f"- **{k}**: {v}")
            lines.append("")

        if topics:
            lines.append(f"## Topics ({len(topics)})")
            for t in topics[:15]:
                lines.append(f"- {t}")
            lines.append("")

        if decisions:
            lines.append(f"## Decisions / Conclusions ({len(decisions)})")
            for d in decisions:
                lines.append(f"- {d}")
            lines.append("")

        if key_terms:
            lines.append(f"## Key Terms ({len(key_terms)})")
            for t in sorted(key_terms)[:20]:
                lines.append(f"- {t}")
            lines.append("")

        if code_blocks:
            lines.append("## Code / Data")
            for cb in code_blocks[:5]:
                lines.append(f"```{cb['language']}")
                lines.append(cb['content'])
                lines.append("```")
                lines.append("")

        if bullets:
            lines.append(f"## Notes ({len(bullets)})")
            for b in bullets[:20]:
                lines.append(f"- {b}")
            lines.append("")

        # Write distilled file
        distilled_name = f"{session_id}--distilled.md"
        distilled_path = distilled_dir / distilled_name
        distilled_path.write_text("\n".join(lines), encoding="utf-8")
        files_written += 1

    return {
        "sessions_processed": len(sessions),
        "distilled_files_written": files_written,
    }


def run_distillation() -> Dict[str, Any]:
    """Run distillation across all Codices with sessions."""
    results: Dict[str, Any] = {
        "sessions_processed": 0,
        "distilled_files_written": 0,
        "by_codex": {},
    }

    for codex_name in _get_all_codexes():
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir():
            continue

        codex_result = distill_sessions(codex_name, codex_dir)
        results["sessions_processed"] += codex_result.get("sessions_processed", 0)
        results["distilled_files_written"] += codex_result.get("distilled_files_written", 0)
        results["by_codex"][codex_name] = codex_result

    return results


# ---------------------------------------------------------------------------
# 3. Archive management
# ---------------------------------------------------------------------------


def run_archive() -> Dict[str, Any]:
    """Archive stale files that are not linked in the entity graph.

    A file is a candidate if:
    - Not modified in STALE_THRESHOLD_DAYS
    - Not registered as a node in the graph (or has no edges)
    - Not already in archive/ or distilled/

    Currently: reports candidates only, does NOT auto-archive.
    (Auto-archival requires explicit opt-in to avoid data loss.)
    """
    result: Dict[str, Any] = {
        "files_archived": 0,
        "candidates": [],
        "errors": [],
    }

    cutoff = datetime.now(timezone.utc).timestamp() - (STALE_THRESHOLD_DAYS * 86400)

    # Check if graph is available to consult
    graph_available = GRAPH_DB.exists()

    for codex_name in _get_all_codexes():
        codex_dir = ATHENAEUM_ROOT / codex_name
        if not codex_dir.is_dir() or codex_name in SYSTEM_CODEXES:
            continue

        for f in codex_dir.rglob("*"):
            if not f.is_file() or f.suffix.lower() not in EMBEDDABLE_EXTS:
                continue
            rel = f.relative_to(ATHENAEUM_ROOT)
            parts = rel.parts
            if len(parts) > 1 and parts[1] in (ARCHIVE_DIR_NAME, DISTILLED_DIR_NAME, SESSIONS_DIR_NAME):
                continue
            if f.name == "INDEX.md":
                continue

            try:
                mtime = f.stat().st_mtime
            except Exception:
                continue

            is_stale = mtime < cutoff

            # If graph is available, check if the file is linked
            is_linked = False
            if graph_available:
                try:
                    import sqlite3
                    conn = sqlite3.connect(str(GRAPH_DB))
                    c = conn.execute(
                        "SELECT id FROM nodes WHERE id = ?",
                        (f"file:{str(rel)}",),
                    )
                    if c.fetchone():
                        is_linked = True
                    conn.close()
                except Exception:
                    pass

            if is_stale and not is_linked:
                result["candidates"].append({
                    "path": str(rel),
                    "codex": codex_name,
                    "last_modified": datetime.fromtimestamp(mtime, tz=timezone.utc).isoformat(),
                    "size": f.stat().st_size,
                })

    # Sort by last_modified (oldest first)
    result["candidates"].sort(key=lambda x: x["last_modified"])

    return result


# ---------------------------------------------------------------------------
# 4. LLM Compilation — compile un-compiled sessions into knowledge articles
# ---------------------------------------------------------------------------

# Codex classification heuristics matching AGENTS.md section 2
CODEX_CLASSIFIERS = [
    # (keywords, codex_name)
    # Check more specific patterns first — order matters
    (["music", "lyric", "song", "vocal", "melody", "chord", "beat", "skc"], "Codex-SKC"),
    (["it helpdesk", "jira", "ticket", "sprint", "standup", "okr"], "Codex-Work"),
    (["infrastructure", "homelab", "proxmox", "docker", "kubernetes", "nginx", "network"], "Codex-Infrastructure"),
    (["health", "medical", "symptom", "diagnosis", "treatment", "doctor", "patient", "asclepius"], "Codex-Asclepius"),
    (["fiction", "worldbuilding", "narrative", "story", "novel", "character", "plot"], "Codex-Fiction"),
    (["code", "python", "javascript", "api", "function", "class", "bug", "feature", "refactor"], "Codex-Forge"),
    (["gateway", "hermes", "pantheon", "session", "agent", "config", "plugin"], "Codex-Pantheon"),
    (["user profile", "personal", "relationship", "family", "hobby", "preference"], "Codex-User"),
]

_DEFAULT_CODEX = "Codex-General"

# Max articles to request per session in the LLM prompt
_MAX_ARTICLES_PER_SESSION = 5
# Max retries for a single session compilation
_MAX_COMPILE_RETRIES = 3
# Base URLs resolved in order of preference
_OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"


def _classify_session(messages: List[Dict]) -> str:
    """Classify a session's domain based on message content.

    Uses simple keyword heuristics matching the AGENTS.md classification table.
    Returns the Codex name (e.g. 'Codex-Forge') or 'Codex-General' as fallback.
    """
    # Collect all text content from messages
    text_pool = ""
    for msg in messages:
        content = msg.get("content", "")
        if isinstance(content, str):
            text_pool += content.lower() + " "
        elif isinstance(content, list):
            for part in content:
                if isinstance(part, dict) and part.get("type") == "text":
                    text_pool += part.get("text", "").lower() + " "

    for keywords, codex in CODEX_CLASSIFIERS:
        for kw in keywords:
            if kw in text_pool:
                return codex

    return _DEFAULT_CODEX


def _format_transcript_md(session_id: str, messages: List[Dict]) -> str:
    """Format session messages into a cleaned markdown transcript.

    Follows the AGENTS.md Layer 2 transcript format.
    Strips base64 image data and other binary content.
    """
    md_parts = []
    md_parts.append(f"# Session: {session_id}")
    md_parts.append("")

    # Count tokens roughly (chars / 4)
    total_chars = sum(len(str(m.get("content", ""))) for m in messages)
    token_estimate = total_chars // 4

    # Estimate duration from timestamps
    timestamps = [m.get("timestamp", 0) for m in messages if m.get("timestamp")]
    duration_min = 0
    if len(timestamps) >= 2:
        duration_min = int((max(timestamps) - min(timestamps)) / 60)

    exchange_num = 0
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")

        # Clean content — strip base64 images and null bytes
        if isinstance(content, str):
            # Remove base64 inline images (data:image/...;base64,...)
            import re as _re
            content = _re.sub(r'data:image/[^;]+;base64,[^\s"\']+', "[image]", content)
            # Remove null bytes
            content = content.replace("\x00", "")
        elif isinstance(content, list):
            # Multimodal content — extract text parts only
            text_parts = []
            for part in content:
                if isinstance(part, dict) and part.get("type") == "text":
                    text_parts.append(part.get("text", ""))
            content = "\n".join(text_parts) if text_parts else "[multimodal content]"

        if not content or not isinstance(content, str):
            continue

        content = content.strip()
        if not content:
            continue

        if role == "user":
            exchange_num += 1
            md_parts.append(f"## Exchange {exchange_num}")
            md_parts.append("")
            md_parts.append(f"**User:** {content[:2000]}")
            md_parts.append("")
        elif role == "assistant":
            reasoning = msg.get("reasoning", "") or msg.get("reasoning_content", "")
            if reasoning:
                if isinstance(reasoning, str) and reasoning.strip():
                    md_parts.append(f"**Reasoning:** {reasoning[:500]}")
            md_parts.append(f"**Assistant:** {content[:3000]}")
            md_parts.append("")
        elif role == "tool":
            # Omit verbose tool results in transcript — summarize
            tool_name = msg.get("tool_name", "")
            if tool_name:
                md_parts.append(f"*[Tool: {tool_name} — result truncated]*")
            else:
                md_parts.append("*[Tool result — truncated]*")
            md_parts.append("")

    return "\n".join(md_parts)


def _format_compilation_prompt(session_id: str, transcript_md: str, codex: str, agents_md: str) -> str:
    """Build the LLM prompt for session compilation following AGENTS.md."""
    existing_codexes = _get_all_codexes()
    codex_list = "\n".join(f"- {c}" for c in existing_codexes)
    return f"""You are the Athenaeum Compiler. Your job is to compile a conversation session into permanent, searchable knowledge articles. Follow the schema in AGENTS.md.

## Context
- **Assigned Codex:** {codex}
- **Session ID:** {session_id}

## Existing Codices
{codex_list}

## Compiler Specification (AGENTS.md)
{agents_md}

## Session Transcript
```markdown
{transcript_md[:8000]}
```

## Instructions
1. First, verify the **Assigned Codex** above. Does this session truly belong there?
   - If the session's primary topic matches an existing Codex well → keep it, set "codex_verification" to the existing name
   - If the session's topic doesn't fit any existing Codex → suggest a new one (e.g. "Codex-HyMem") with a clear reason
2. Identify 1-{_MAX_ARTICLES_PER_SESSION} distinct knowledge articles from this session
3. For each: determine if it's a new concept, a connection between concepts, or a Q&A filing
4. Output ONLY valid JSON in the following format — no markdown wrapping, no explanation:

```json
{{
  "codex_verification": "Codex-Forge",
  "codex_reason": "Session is about Python API development — fits Codex-Forge perfectly.",
  "articles": [
    {{
      "type": "concept|connection|qa",
      "name": "kebab-case-article-name",
      "title": "Human Readable Title",
      "summary": "One-line summary of the article",
      "content": "Article body in markdown format. For concepts: core explanation, key points, details. For connections: the link, key insight, evidence. For Q&A: answer, sources consulted.",
      "tags": ["tag1", "tag2"],
      "action": "create"
    }}
  ]
}}
```

For new codex suggestions, "codex_verification" should be the new name (e.g. "Codex-HyMem") and "codex_reason" should explain why no existing codex fits.

## Important guidelines
- Prefer updating existing articles over creating near-duplicates
- If the session reveals a non-obvious connection, create a connections/ article
- If significant Q&A was exchanged, create a qa/ article
- Write in encyclopedia style — factual, concise, self-contained
- A single session typically produces 1-3 articles
- Return ONLY the JSON — no other text."""


def _call_llm_for_compilation(prompt: str) -> Optional[Dict]:
    """Call the LLM (via OpenCode Go) to compile a session.

    Returns parsed JSON response dict or None on failure.
    Uses the same transport as entity extraction (OpenCode Go + minimax-m2.5).
    """
    api_key = os.environ.get("OPENCODE_GO_API_KEY") or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        logger.warning("No API key found for LLM compilation (set OPENCODE_GO_API_KEY or OPENAI_API_KEY)")
        return None

    model = os.environ.get("ATHENAEUM_EXTRACT_MODEL", "minimax-m2.5")
    base_url = os.environ.get("OPENCODE_GO_BASE_URL", "https://opencode.ai/zen/go/v1/chat/completions")

    try:
        import httpx

        resp = httpx.post(
            base_url,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 4096,
                "temperature": 0.3,
            },
            timeout=300,  # 5 min — compilation prompts are large (AGENTS.md + transcript)
        )
        resp.raise_for_status()
        data = resp.json()
        msg = data["choices"][0]["message"]
        content = (msg.get("content") or "").strip()
        if not content:
            reasoning = msg.get("reasoning_content", "")
            if reasoning and reasoning.strip():
                content = reasoning.strip()
        if not content:
            logger.warning("Empty response from LLM compilation")
            return None

        # Strip markdown code fences if present
        if content.startswith("```"):
            import re as _re
            m = _re.match(r"```(?:json)?\s*\n?(.*?)\n?```", content, _re.DOTALL)
            if m:
                content = m.group(1).strip()

        result = json.loads(content)
        if not isinstance(result, dict) or "articles" not in result:
            logger.warning("LLM response missing 'articles' key")
            return None

        return result
    except Exception as exc:
        # Log detailed error info — crucial for debugging rate limits, timeouts, bad responses
        if hasattr(exc, 'response') and exc.response is not None:
            try:
                resp_body = exc.response.text[:500]
            except Exception:
                resp_body = "<unreadable>"
            logger.warning("LLM compilation call failed [HTTP %d]: %s — %s",
                         exc.response.status_code, exc, resp_body)
        elif isinstance(exc, httpx.TimeoutException):
            logger.warning("LLM compilation call timed out (300s): %s", exc)
        else:
            logger.warning("LLM compilation call failed (%s): %s", type(exc).__name__, exc)
        return None


def _write_articles(codex: str, session_id: str, articles: List[Dict]) -> Dict[str, int]:
    """Write compiled articles to the Codex's distilled/ directory.

    Returns counts: {created, updated, by_type}.
    """
    codex_dir = ATHENAEUM_ROOT / codex
    distilled_dir = codex_dir / DISTILLED_DIR_NAME
    concepts_dir = distilled_dir / "concepts"
    connections_dir = distilled_dir / "connections"
    qa_dir = distilled_dir / "qa"

    for d in [concepts_dir, connections_dir, qa_dir]:
        d.mkdir(parents=True, exist_ok=True)

    created = 0
    updated = 0
    by_type = {"concept": 0, "connection": 0, "qa": 0}

    for article in articles:
        art_type = article.get("type", "concept")
        name = article.get("name", "")
        title = article.get("title", name)
        content_body = article.get("content", "")
        summary = article.get("summary", "")
        tags = article.get("tags", [])

        if not name:
            continue

        if art_type == "concept":
            target_dir = concepts_dir
        elif art_type == "connection":
            target_dir = connections_dir
        elif art_type == "qa":
            target_dir = qa_dir
        else:
            target_dir = concepts_dir  # fallback

        article_path = target_dir / f"{name}.md"
        action = article.get("action", "create")

        # Build YAML frontmatter
        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        frontmatter = [
            "---",
            f"title: \"{title}\"",
        ]
        if tags:
            frontmatter.append(f"tags: {json.dumps(tags)}")
        frontmatter.append(f"sources:")
        frontmatter.append(f"  - \"{codex}/sessions/{session_id}.md\"")
        if action == "update":
            frontmatter.append(f"updated: {now_iso}")
        else:
            frontmatter.append(f"created: {now_iso}")
            frontmatter.append(f"updated: {now_iso}")
        frontmatter.append("---")
        frontmatter.append("")
        frontmatter.append(f"# {title}")
        frontmatter.append("")
        frontmatter.append(content_body)

        article_content = "\n".join(frontmatter)
        article_path.write_text(article_content, encoding="utf-8")

        if action == "update" and article_path.exists():
            updated += 1
        else:
            created += 1
        by_type[art_type] = by_type.get(art_type, 0) + 1

        logger.info("  → %s %s: %s (%s)", "Updated" if action == "update" else "Created", art_type, name, codex)

    # Update INDEX.md
    index_path = distilled_dir / "INDEX.md"
    if not index_path.exists():
        index_lines = [
            f"# Distilled Knowledge Index — {codex}",
            "",
            "| Article | Type | Summary | Compiled From | Updated |",
            "|---|---|---|---|---|",
        ]
    else:
        index_lines = index_path.read_text(encoding="utf-8").strip().split("\n")

    for article in articles:
        art_type = article.get("type", "concept")
        name = article.get("name", "")
        summary = article.get("summary", "")
        now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        # Parts referencing the article
        type_label = {"concept": "concept", "connection": "connection", "qa": "qa"}.get(art_type, art_type)
        index_lines.append(
            f"| [[{type_label}s/{name}]] | {type_label} | {summary} | {session_id} | {now_iso} |"
        )

    index_path.write_text("\n".join(index_lines) + "\n", encoding="utf-8")

    # Append to compilation-log.md
    log_path = distilled_dir / "compilation-log.md"
    log_entry = (
        f"## {datetime.now(timezone.utc).isoformat()}\n"
        f"- **Session:** {session_id}\n"
        f"- **Codex:** {codex}\n"
        f"- **Articles:** {len(articles)}\n\n"
    )
    with open(log_path, "a", encoding="utf-8") as f:
        f.write(log_entry)

    return {"created": created, "updated": updated, "by_type": by_type}


def _copy_transcript_to_codex(session_id: str, transcript_md: str, codex: str) -> bool:
    """Copy a cleaned session transcript to Codex-{domain}/sessions/."""
    sessions_dir = ATHENAEUM_ROOT / codex / SESSIONS_DIR_NAME
    sessions_dir.mkdir(parents=True, exist_ok=True)

    transcript_path = sessions_dir / f"{session_id}.md"
    transcript_path.write_text(transcript_md, encoding="utf-8")
    logger.info("  → Transcript copied: %s/%s/%s.md", codex, SESSIONS_DIR_NAME, session_id)
    return True


def _load_agents_md() -> str:
    """Load the AGENTS.md compiler spec."""
    agents_path = ATHENAEUM_ROOT / "AGENTS.md"
    if agents_path.exists():
        return agents_path.read_text(encoding="utf-8")
    logger.warning("AGENTS.md not found at %s", agents_path)
    return ""


def llm_compile_session(session_id: str, messages: List[Dict], agents_md: str) -> Optional[Dict]:
    """Compile a single session transcript into knowledge articles.

    Args:
        session_id: The session to compile.
        messages: The session messages from state.db.
        agents_md: The AGENTS.md compiler specification content.

    Returns:
        Dict with compilation results, or None on failure.
    """
    logger.info("Compiling session %s (%d messages)...", session_id, len(messages))

    # Classify domain
    codex = _classify_session(messages)
    logger.info("  → Classified as: %s", codex)

    # Format transcript
    transcript_md = _format_transcript_md(session_id, messages)
    logger.info("  → Transcript: %d chars", len(transcript_md))

    # Build LLM prompt
    prompt = _format_compilation_prompt(session_id, transcript_md, codex, agents_md)
    logger.info("  → Prompt: %d chars", len(prompt))

    # Call LLM
    result = _call_llm_for_compilation(prompt)
    if not result:
        logger.warning("  → LLM compilation returned no result")
        return None

    articles = result.get("articles", [])
    if not articles:
        logger.warning("  → No articles in LLM response")
        return None

    logger.info("  → LLM returned %d articles", len(articles))

    # Check if LLM suggests a different or new Codex
    verified_codex = result.get("codex_verification", "")
    if verified_codex and verified_codex != codex:
        logger.info("  → LLM suggests reclassifying to: %s (was: %s)", verified_codex, codex)
        codex = verified_codex

        # Auto-create if it doesn't exist yet
        if not (ATHENAEUM_ROOT / codex).exists():
            reason = result.get("codex_reason", f"Auto-created by LLM compilation of session {session_id}")
            _create_codex(codex, description=reason[:200])
            new_codex_created = codex
            logger.info("  → ✨ New Codex auto-created: %s", codex)
        else:
            new_codex_created = None
    else:
        new_codex_created = None

    # Write articles to Athenaeum
    write_result = _write_articles(codex, session_id, articles)

    # Copy cleaned transcript to Codex
    _copy_transcript_to_codex(session_id, transcript_md, codex)

    return {
        "session_id": session_id,
        "codex": codex,
        "articles": articles,
        "articles_created": write_result["created"],
        "articles_updated": write_result["updated"],
        "articles_by_type": write_result["by_type"],
        "new_codex_created": new_codex_created,
    }


def run_compilation(limit: int = 5) -> Dict[str, Any]:
    """Run LLM compilation on un-compiled sessions.

    Args:
        limit: Max sessions to compile this run (default 5, for the Beelink's 7.2GB RAM).

    Returns:
        Compilation result dict matching HadesReport.compilation shape.
    """
    result: Dict[str, Any] = {
        "sessions_compiled": 0,
        "articles_created": 0,
        "articles_updated": 0,
        "articles_by_type": {"concept": 0, "connection": 0, "qa": 0},
        "transcripts_copied": 0,
        "errors": [],
        "batch_size": limit,
        "total_backlog": 0,
        "new_codexes_created": [],
    }

    # Load AGENTS.md spec
    agents_md = _load_agents_md()
    if not agents_md:
        result["errors"].append("AGENTS.md not found — cannot compile")
        return result

    # Connect to state.db
    try:
        from hermes_state import SessionDB
        state_db = SessionDB()
    except Exception as exc:
        result["errors"].append(f"Failed to connect to state.db: {exc}")
        logger.exception("state.db connection error")
        return result

    # Get un-compiled sessions
    total_backlog = state_db.count_uncompiled()
    result["total_backlog"] = total_backlog
    logger.info("Compilation backlog: %d un-compiled sessions", total_backlog)

    if total_backlog == 0:
        logger.info("No un-compiled sessions found. Nothing to do.")
        return result

    sessions_to_compile = state_db.get_uncompiled_sessions(limit=limit)
    logger.info("Processing %d sessions (limit=%d)...", len(sessions_to_compile), limit)

    for session_info in sessions_to_compile:
        session_id = session_info["id"]
        try:
            # Load messages from state.db
            messages = state_db.get_messages(session_id)
            if not messages:
                logger.info("  → Session %s has no messages, marking as compiled (empty)", session_id)
                state_db.mark_compiled(session_id)
                result["sessions_compiled"] += 1
                continue

            # Compile with retry
            compile_result = None
            for attempt in range(_MAX_COMPILE_RETRIES):
                compile_result = llm_compile_session(session_id, messages, agents_md)
                if compile_result is not None:
                    break
                if attempt < _MAX_COMPILE_RETRIES - 1:
                    import time as _time
                    _time.sleep(2 ** attempt)  # Exponential backoff: 1s, 2s, 4s...
                logger.warning("  → Retry %d/%d for session %s", attempt + 1, _MAX_COMPILE_RETRIES, session_id)

            if compile_result is None:
                result["errors"].append(f"Failed to compile session {session_id} after {_MAX_COMPILE_RETRIES} retries")
                continue  # Leave compiled=0 so it's retried next run

            # Mark as compiled
            state_db.mark_compiled(session_id)

            # Aggregate results
            result["sessions_compiled"] += 1
            result["articles_created"] += compile_result.get("articles_created", 0)
            result["articles_updated"] += compile_result.get("articles_updated", 0)
            result["transcripts_copied"] += 1
            for art_type, count in compile_result.get("articles_by_type", {}).items():
                result["articles_by_type"][art_type] = result["articles_by_type"].get(art_type, 0) + count

            new_cx = compile_result.get("new_codex_created")
            if new_cx:
                result["new_codexes_created"].append(new_cx)

            logger.info("  ✓ Session %s compiled: %d created, %d updated",
                        session_id,
                        compile_result.get("articles_created", 0),
                        compile_result.get("articles_updated", 0))

        except Exception as exc:
            err_msg = f"Error compiling session {session_id}: {exc}"
            result["errors"].append(err_msg)
            logger.exception(err_msg)
            # Leave compiled=0 — will be retried next run
            continue

    # Update backlog count
    try:
        result["total_backlog"] = state_db.count_uncompiled()
    except Exception:
        pass

    return result


# ---------------------------------------------------------------------------
# 5. Codex-General cluster detection — find unclassified topic clusters
# ---------------------------------------------------------------------------


def _scan_general_for_codexes(min_cluster_size: int = 5) -> List[Dict]:
    """Scan Codex-General for topic clusters and auto-create new Codices.

    Reads files in Codex-General's root (not sessions/distilled/archive),
    extracts topic keywords from content, and creates new Codexes when
    a topic cluster exceeds min_cluster_size files.

    Args:
        min_cluster_size: Minimum files sharing a keyword to form a cluster

    Returns:
        List of dicts with {codex, keyword, files_moved} for new Codexes created.
    """
    general_dir = ATHENAEUM_ROOT / "Codex-General"
    if not general_dir.is_dir():
        return []

    created_codexes: List[Dict] = []
    keyword_clusters: Dict[str, List[str]] = {}

    # Collect all non-special files in the root of Codex-General
    # (not sessions/, distilled/, or archive/ subdirs)
    files_to_scan = list(general_dir.glob("*.md"))
    if len(files_to_scan) < min_cluster_size:
        return []  # Not enough files to bother

    # For each file, extract topic keywords from frontmatter, title, or first line
    import re as _re

    for f in files_to_scan:
        if f.name.startswith("INDEX"):
            continue
        try:
            content = f.read_text(encoding="utf-8", errors="replace")[:2000]
        except Exception:
            continue

        # Try to get title from frontmatter or first heading
        title_match = _re.search(r"^#\s+(.+)", content, _re.MULTILINE)
        if not title_match:
            continue

        title = title_match.group(1).strip().lower()
        # Extract meaningful keywords (words 4+ chars, skip common words)
        words = _re.findall(r"\b[a-z]{4,}\b", title)
        stopwords = {"this", "that", "with", "from", "have", "been", "will",
                     "what", "when", "where", "which", "their", "there"}
        keywords = [w for w in words if w not in stopwords]

        for kw in set(keywords):
            if kw not in keyword_clusters:
                keyword_clusters[kw] = []
            keyword_clusters[kw].append(str(f.relative_to(ATHENAEUM_ROOT)))

    # Find clusters above threshold
    clusters = [(kw, files) for kw, files in keyword_clusters.items()
                if len(files) >= min_cluster_size]

    if not clusters:
        logger.info("  → No topic clusters found in Codex-General")
        return []

    # Sort by cluster size (largest first)
    clusters.sort(key=lambda x: len(x[1]), reverse=True)

    logger.info("  → Found %d topic clusters in Codex-General", len(clusters))

    for keyword, files in clusters[:3]:  # Max 3 new codexes per run
        codex_name = f"Codex-{keyword.capitalize()}"
        if (ATHENAEUM_ROOT / codex_name).exists():
            continue  # Already exists, skip

        created = _create_codex(
            codex_name,
            description=f"Auto-detected from Codex-General cluster: {len(files)} files about '{keyword}'"
        )
        if not created:
            continue

        # Move files to the new Codex
        moved = 0
        for rel_path in files:
            src = ATHENAEUM_ROOT / rel_path
            dest = ATHENAEUM_ROOT / codex_name / src.name
            try:
                src.rename(dest)
                moved += 1
            except Exception as exc:
                logger.warning("  → Failed to move %s: %s", src.name, exc)

        created_codexes.append({
            "codex": codex_name,
            "keyword": keyword,
            "files_moved": moved,
        })
        logger.info("  → ✨ Codex %s created with %d files from '%s' cluster",
                     codex_name, moved, keyword)

    if created_codexes:
        logger.info("  → Total new Codexes from General scan: %d", len(created_codexes))

    return created_codexes


# ---------------------------------------------------------------------------
# 6. Mailbox delivery — send report to Hermes
# ---------------------------------------------------------------------------


def _msg_id() -> str:
    """Generate a unique message ID based on timestamp."""
    return datetime.now(timezone.utc).strftime("msg_%Y%m%d_%H%M%S_%f")[:26]


# ---------------------------------------------------------------------------
# 5. Shared Context Sweep
# ---------------------------------------------------------------------------


SHARED_CONTEXT_ROOT = Path(f"{_REAL_HOME}/pantheon/shared")
SHARED_CUTOFF_HOURS = 24


def run_shared_context_sweep() -> Dict[str, Any]:
    """Scan ~/pantheon/shared/ for entries >24h old and consolidate them.

    Decisions (>24h): Copy to Codex-Pantheon/decisions/ and remove from shared.
    Active tasks (>24h): Move from active/ to archive/ (stale — no longer current).
    athenaeum-writes.md: Already in Athenaeum, just count entries for the report.
    """
    result: Dict[str, Any] = {
        "decisions_ingested": 0,
        "active_archived": 0,
        "athenaeum_entries": 0,
        "errors": [],
    }
    cutoff = datetime.now(timezone.utc) - timedelta(hours=SHARED_CUTOFF_HOURS)

    if not SHARED_CONTEXT_ROOT.is_dir():
        result["errors"].append(f"Shared context root not found: {SHARED_CONTEXT_ROOT}")
        return result

    # ── Sweep decisions/ ──────────────────────────────────────────────
    decisions_dir = SHARED_CONTEXT_ROOT / "decisions"
    if decisions_dir.is_dir():
        decisions_codex = ATHENAEUM_ROOT / "Codex-Pantheon" / "decisions"
        decisions_codex.mkdir(parents=True, exist_ok=True)

        for f in sorted(decisions_dir.glob("*.md")):
            if f.name == "INDEX.md":
                continue
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    # Copy to Codex-Pantheon/decisions/
                    dest = decisions_codex / f.name
                    shutil.copy2(str(f), str(dest))
                    f.unlink()
                    result["decisions_ingested"] += 1
                    logger.info("  → Ingested decision: %s → Codex-Pantheon/decisions/", f.name)
            except Exception as exc:
                result["errors"].append(f"Failed to process decision {f.name}: {exc}")
                logger.warning("  → Decision sweep error: %s — %s", f.name, exc)

    # ── Sweep active/ ─────────────────────────────────────────────────
    active_dir = SHARED_CONTEXT_ROOT / "active"
    archive_dir = SHARED_CONTEXT_ROOT / "archive"
    archive_dir.mkdir(parents=True, exist_ok=True)

    if active_dir.is_dir():
        for f in sorted(active_dir.glob("*.md")):
            if f.name == "INDEX.md":
                continue
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
                if mtime < cutoff:
                    # Move to archive/ — no longer current
                    dest = archive_dir / f.name
                    shutil.move(str(f), str(dest))
                    result["active_archived"] += 1
                    logger.info("  → Archived stale active task: %s", f.name)
            except Exception as exc:
                result["errors"].append(f"Failed to archive active task {f.name}: {exc}")
                logger.warning("  → Active archive error: %s — %s", f.name, exc)

    # ── Count athenaeum-writes.md entries ─────────────────────────────
    aw_path = SHARED_CONTEXT_ROOT / "athenaeum-writes.md"
    if aw_path.exists():
        try:
            content = aw_path.read_text(encoding="utf-8")
            # Count non-header, non-empty lines
            entries = [l for l in content.split("\n") if l.strip() and not l.startswith("#") and not l.startswith("*")]
            result["athenaeum_entries"] = len(entries)
        except Exception as exc:
            result["errors"].append(f"Failed to read athenaeum-writes.md: {exc}")

    return result


def deliver_to_mailbox(report: HadesReport) -> Optional[str]:
    """Send the Hades report as a JSON message to Hermes' inbox.

    Returns the message file path if delivered, None on failure.
    """
    try:
        HERMES_INBOX.mkdir(parents=True, exist_ok=True)

        msg_id = _msg_id()
        markdown = report.to_markdown()
        health = report.health or {}
        dist = report.distillation or {}
        arch = report.archive or {}

        # Build a concise summary for the body
        summary_parts = []
        if health.get("indexes_created"):
            summary_parts.append(f"📄 Auto-created {len(health['indexes_created'])} INDEX.md files")
        orphans_fs = health.get("orphans", {}).get("fs_unembedded", [])
        if orphans_fs:
            summary_parts.append(f"⚠️ {len(orphans_fs)} files not embedded in ChromaDB")
        if dist.get("distilled_files_written", 0) > 0:
            summary_parts.append(f"🔄 Distilled {dist['distilled_files_written']} files")
        if arch.get("candidates"):
            summary_parts.append(f"🗄️ {len(arch['candidates'])} archive candidates found")
        sc = report.shared_context or {}
        if sc.get("decisions_ingested", 0) > 0 or sc.get("active_archived", 0) > 0:
            parts = []
            if sc.get("decisions_ingested"):
                parts.append(f"{sc['decisions_ingested']} decisions")
            if sc.get("active_archived"):
                parts.append(f"{sc['active_archived']} tasks archived")
            summary_parts.append(f"📋 Shared context: {', '.join(parts)}")
        extr = report.extraction or {}
        if extr.get("entities_extracted", 0) > 0:
            summary_parts.append(f"🔗 {extr['entities_extracted']} entities, {extr['relations_extracted']} relations")
        elif extr.get("error"):
            summary_parts.append(f"🔗 Extraction error: {extr['error'][:60]}")
        comp = report.compilation or {}
        if comp.get("sessions_compiled", 0) > 0:
            summary_parts.append(f"🧠 Compiled {comp['sessions_compiled']} sessions → {comp['articles_created']} articles")
        if comp.get("errors"):
            summary_parts.append(f"🧠 {len(comp['errors'])} compilation errors")
        if report.errors:
            summary_parts.append(f"❌ {len(report.errors)} errors during run")

        summary = " • ".join(summary_parts) if summary_parts else "No issues detected."

        message = {
            "id": msg_id,
            "from": "hephaestus",
            "to": "hermes",
            "type": "report",
            "subject": f"Hades Nightly Report — {report.timestamp[:10]}",
            "body": f"Hades consolidation pipeline ran at {report.timestamp[:19]}.\n\n{summary}\n\n---\n\nFull report:\n{markdown}",
            "priority": "normal",
            "timestamp": report.timestamp,
            "read": False,
            "payload": {
                "report_type": "hades_nightly",
                "date": report.timestamp[:10],
                "indexes_created": len(health.get("indexes_created", [])),
                "files_unembedded": len(orphans_fs),
                "distilled_written": dist.get("distilled_files_written", 0),
                "archive_candidates": len(arch.get("candidates", [])),
                "entities_extracted": extr.get("entities_extracted", 0),
                "relations_extracted": extr.get("relations_extracted", 0),
                "shared_decisions_ingested": sc.get("decisions_ingested", 0),
                "shared_active_archived": sc.get("active_archived", 0),
                "sessions_compiled": comp.get("sessions_compiled", 0),
                "articles_created": comp.get("articles_created", 0),
                "errors": len(report.errors),
            },
            "thread_id": None,
        }

        msg_path = HERMES_INBOX / f"{msg_id}.json"
        msg_path.write_text(json.dumps(message, indent=2, default=str), encoding="utf-8")
        logger.info("  → Report delivered to Hermes mailbox: %s", msg_path.name)
        return str(msg_path)

    except Exception as exc:
        logger.exception("Failed to deliver report to Hermes mailbox: %s", exc)
        return None


# ---------------------------------------------------------------------------
# 7. Full Hades run
# ---------------------------------------------------------------------------


def run_hades(compile_limit: int = 5) -> HadesReport:
    """Run the complete Hades consolidation pipeline.

    Returns a HadesReport with all findings.
    """
    report = HadesReport()
    start = time.time()

    # Load environment variables from .env files for in-process operations
    # (compilation, distillation) — extraction subprocess loads its own
    _home = os.path.expanduser("~")
    for _env_path in [Path(f"{_home}/.hermes/.env"), Path(f"{_home}/pantheon/.env")]:
        if _env_path.exists():
            for line in _env_path.read_text().split("\n"):
                line = line.strip()
                if line and "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    v = v.strip().strip("'\"")
                    os.environ.setdefault(k.strip(), v)

    try:
        # Phase 1: Health checks
        logger.info("Hades: Running health checks...")
        try:
            health = run_health_checks()
            report.health = health
            logger.info("  → %d codexes checked", len(health.get("codexes", {})))
        except Exception as exc:
            report.errors.append(f"Health checks failed: {exc}")
            logger.exception("Hades health check error")

        # Phase 2: Distillation
        logger.info("Hades: Running distillation...")
        try:
            dist = run_distillation()
            report.distillation = dist
            logger.info("  → %d sessions → %d distilled files",
                         dist.get("sessions_processed", 0),
                         dist.get("distilled_files_written", 0))
        except Exception as exc:
            report.errors.append(f"Distillation failed: {exc}")
            logger.exception("Hades distillation error")

        # Phase 3: Archive scan
        logger.info("Hades: Scanning for archive candidates...")
        try:
            arch = run_archive()
            report.archive = arch
            logger.info("  → %d archive candidates found", len(arch.get("candidates", [])))
        except Exception as exc:
            report.errors.append(f"Archive scan failed: {exc}")
            logger.exception("Hades archive error")

        # Phase 4: Shared Context Sweep — ingest >24h entries from ~/pantheon/shared/
        logger.info("Hades: Running shared context sweep...")
        try:
            sc = run_shared_context_sweep()
            report.shared_context = sc
            logger.info("  → %d decisions ingested, %d active tasks archived",
                         sc.get("decisions_ingested", 0),
                         sc.get("active_archived", 0))
            if sc.get("errors"):
                logger.warning("  → %d shared context errors", len(sc["errors"]))
        except Exception as exc:
            report.errors.append(f"Shared context sweep failed: {exc}")
            logger.exception("Hades shared context sweep error")

        # Phase 5: Entity extraction from Athenaeum files
        logger.info("Hades: Running entity extraction...")
        try:
            _REAL_HOME = os.path.expanduser("~")
            extract_script = os.path.join(_REAL_HOME, "athenaeum", "scripts", "extract-entities.py")
            if os.path.exists(extract_script):
                import subprocess, sys
                env = os.environ.copy()
                for _env_path in [Path(f"{_REAL_HOME}/.hermes/.env"), Path(f"{_REAL_HOME}/.hermes/profiles/hephaestus/.env"), Path(f"{_REAL_HOME}/pantheon/.env")]:
                    if _env_path.exists():
                        for line in _env_path.read_text().split("\n"):
                            line = line.strip()
                            if line and "=" in line and not line.startswith("#"):
                                k, v = line.split("=", 1)
                                env.setdefault(k.strip(), v.strip().strip("'\""))
                result = subprocess.run(
                    [sys.executable, extract_script, "--workers", "4"],
                    capture_output=True, text=True, timeout=3600, env=env,
                )
                if result.returncode == 0:
                    # Parse summary from output
                    for line in result.stdout.split("\n"):
                        if "Total entities extracted:" in line:
                            try:
                                report.extraction["entities_extracted"] = int(line.split(":")[-1].strip())
                            except (ValueError, IndexError):
                                pass
                        elif "Total relations extracted:" in line:
                            try:
                                report.extraction["relations_extracted"] = int(line.split(":")[-1].strip())
                            except (ValueError, IndexError):
                                pass
                        elif "Processed:" in line and "files" in line.lower():
                            try:
                                report.extraction["files_processed"] = int(line.split(":")[-1].strip().split()[0])
                            except (ValueError, IndexError):
                                pass
                        elif "Failed:" in line and "files" in line.lower():
                            try:
                                report.extraction["files_failed"] = int(line.split(":")[-1].strip().split()[0])
                            except (ValueError, IndexError):
                                pass
                    logger.info("  → %d entities, %d relations extracted",
                                 report.extraction["entities_extracted"],
                                 report.extraction["relations_extracted"])
                else:
                    err = result.stderr.strip()[:2000] if result.stderr.strip() else "exit code != 0"
                    report.extraction["error"] = f"extract-entities failed: {err}"
                    logger.warning("  → Entity extraction failed: %s", err)
            else:
                report.extraction["error"] = f"Script not found: {extract_script}"
                logger.warning("  → Entity extraction script not found")
        except subprocess.TimeoutExpired:
            report.extraction["error"] = "extract-entities timed out after 20m"
            logger.warning("  → Entity extraction timed out")
        except Exception as exc:
            report.extraction["error"] = f"Entity extraction error: {exc}"
            logger.exception("Hades entity extraction error")

        # Phase 6: LLM Compilation — compile un-compiled sessions into knowledge articles
        if compile_limit > 0:
            logger.info("Hades: Running LLM compilation (limit=%d)...", compile_limit)
            try:
                comp = run_compilation(limit=compile_limit)
                report.compilation = comp
                logger.info("  → %d sessions compiled, %d articles created, %d errors",
                             comp.get("sessions_compiled", 0),
                             comp.get("articles_created", 0),
                             len(comp.get("errors", [])))
            except Exception as exc:
                report.errors.append(f"LLM compilation failed: {exc}")
                logger.exception("Hades compilation error")
        else:
            logger.info("Hades: LLM compilation skipped (--no-compile)")

        # Phase 7: Scan Codex-General for topic clusters → auto-create new Codices
        logger.info("Hades: Scanning Codex-General for topic clusters...")
        try:
            new_codexes = _scan_general_for_codexes()
            if new_codexes:
                report.health["new_codexes"] = new_codexes
                logger.info("  → %d new Codexes created from General scan", len(new_codexes))
        except Exception as exc:
            report.errors.append(f"Codex-General scan failed: {exc}")

        # Phase 8: Deliver report to Hermes mailbox
        logger.info("Hades: Delivering report to Hermes mailbox...")
        try:
            msg_path = deliver_to_mailbox(report)
            if msg_path:
                logger.info("  → Delivered: %s", msg_path)
        except Exception as exc:
            report.errors.append(f"Mailbox delivery failed: {exc}")
            logger.exception("Hades mailbox delivery error")

        elapsed = time.time() - start
        logger.info("Hades complete in %.2fs", elapsed)

        # Phase 9: Write heartbeat for the Fates
        import sys
        _hades_scripts = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        try:
            from heartbeat import beat  # noqa: F811
            beat("hades")
            logger.info("  → Heartbeat written")
        except Exception as exc:
            logger.warning("  → Heartbeat write failed (non-fatal): %s", exc)

    except Exception as exc:
        report.errors.append(f"Hades run failed: {exc}")
        logger.exception("Hades run failed")

    return report


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    """Run Hades and print the report to stdout."""
    import argparse

    parser = argparse.ArgumentParser(description="Hades — Athenaeum consolidation pipeline")
    parser.add_argument("--health", action="store_true", help="Run health checks only")
    parser.add_argument("--distill", action="store_true", help="Run distillation only")
    parser.add_argument("--archive", action="store_true", help="Scan archive candidates only")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--save", metavar="PATH", help="Save report to file")
    parser.add_argument("--compile", nargs="?", type=int, const=100, default=100, metavar="N",
                        help="Max sessions to compile (default: 100). Use --no-compile to skip.")
    parser.add_argument("--no-compile", action="store_true", dest="no_compile",
                        help="Skip LLM compilation entirely")

    args = parser.parse_args()

    # Set up logging
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")

    if args.health:
        report = HadesReport()
        report.health = run_health_checks()
    elif args.distill:
        report = HadesReport()
        report.distillation = run_distillation()
    elif args.archive:
        report = HadesReport()
        report.archive = run_archive()
    else:
        compile_limit = 0 if args.no_compile else args.compile
        report = run_hades(compile_limit=compile_limit)

    # Record heartbeat after any mode runs
    try:
        _hades_scripts = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts")
        if _hades_scripts not in sys.path:
            sys.path.insert(0, _hades_scripts)
        from heartbeat import beat  # noqa: F811
        beat("hades")
    except Exception:
        pass

    if args.json:
        output = json.dumps(report.to_dict(), indent=2)
    else:
        output = report.to_markdown()

    print(output)

    if args.save:
        Path(args.save).write_text(output, encoding="utf-8")
        logger.info("Report saved to %s", args.save)


if __name__ == "__main__":
    main()
